development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # for development
  #  url: redis://localhost:6379/1  
  # for production
  url: <%= ENV["REDISCLOUD_URL"] %>
  channel_prefix: restaurant_production
